# Generated by Django 3.1.3 on 2020-11-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0003_auto_20201129_0049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancy',
            new_name='VacancyModel',
        ),
    ]
