# Generated by Django 3.1.3 on 2020-12-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0005_auto_20201129_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('logo', models.URLField(default='https://place-hold.it/100x60')),
                ('description', models.TextField()),
                ('employee_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('description', models.TextField()),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('published_at', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies_app.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancymodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vacancymodel',
            name='specialty',
        ),
        migrations.RenameModel(
            old_name='SpecialtyModel',
            new_name='Specialty',
        ),
        migrations.DeleteModel(
            name='CompanyModel',
        ),
        migrations.DeleteModel(
            name='VacancyModel',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies_app.specialty'),
        ),
    ]
